### PR TITLE
feat: integrate talisman wallet

### PR DESCRIPTION
**Pull request by 0xKheops**
This PR provides a Talisman option in the connect wallet modal.

Please note that by default, Talisman will prevent the user from switching to Avalanche network.
To allow adding and switching to Avalanche, the user needs to go to extension options and toggle on `enable custom networks`.
This limitation should be removed in next Talisman version : it was meant for our EVM beta and has no sense anymore.

### CODE REVIEW

**Review by SarjuHansaliya — CHANGES_REQUESTED** [review]
1. even though I have installed Talisman wallet its showing me Install Talisman option. I am using Firefox
Screenshot 2022-07-14 at 11 20 41 PM

2. With this PR, please also update interface code to show account is connected via Talisman wallet.

**Comment by 0xKheops** [comment]
Hi @SarjuHansaliya 

1. Install link
Button turns into an install link if window.talismanEth doesn't exist. It should be define with Talisman version >= 1.5.0.
Users that installed it from chrome webstore shouldn't have this issue as it updates automatically.
Which version do you have ?

I tested this story book page and Talisman shows up correctly. So i think it's just a Talisman version issue.

2. interface project
Yes, I'm waiting for this PR To be merged before upgrading interface project.

**Comment by SarjuHansaliya** [comment]
@0xKheops 
1. I am using latest version 1.5.4
2. please create interface PR before merging this PR. this PR will get merged after end to end testing with interface.

**Comment by 0xKheops** [comment]
@SarjuHansaliya For the problem that you experience in story book, it's due to story book. If you click the button to open the story in full page mode, it should work fine. I tested both chrome and firefox.

I updated interface as requested, with PR https://github.com/pangolindex/interface/pull/574
It says build failed but I can't access the preview logs (404 page) to investigate why. 
Project builds fine on my machine.
I don't know how to go further, may you please have a look ?

**Comment by SarjuHansaliya** [comment]
thanks @0xKheops I will check out both PRs again today.

**Review by SarjuHansaliya — APPROVED** [review]

**Pull request merged**
